// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Start Today"
          text="Ready to simplify your errands?"
          primaryButton={{
            text: "Get In Touch",        href: "#"}}
          secondaryButton={{
            text: "View Location",        href: "#"}}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
