// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Get Answers"
          title="Commonly Asked Questions"
          description="Everything you need to know about our services."
          items={[
            {
              question: "Are bookings required?",          answer: "For salon yes, but laundry/games are walk-in friendly."},
            {
              question: "Can I bring my own gear?",          answer: "Yes, we encourage using your own peripherals."},
            {
              question: "Is WiFi available?",          answer: "Yes, high-speed fiber throughout the building."},
            {
              question: "Do you offer dry cleaning?",          answer: "Yes, we offer professional dry cleaning services."},
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
