// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsFeatureCards from '@/components/sections/metrics/MetricsFeatureCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsFeatureCards
          tag="Our Impact"
          title="Serving Our Community Daily"
          description="Proven results for busy residents."
          metrics={[
            {
              value: "15k+",          title: "Clothes Washed",          features: [
                "Safe handling",            "Eco-detergents"],
            },
            {
              value: "5k+",          title: "Style Refreshments",          features: [
                "Professional stylists",            "High-end products"],
            },
            {
              value: "2k+",          title: "Gaming Sessions",          features: [
                "High FPS",            "Pro controllers"],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
