// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingSimpleCards from '@/components/sections/pricing/PricingSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingSimpleCards
          tag="Membership Options"
          title="Flexible Plans for You"
          description="Choose the membership that fits your lifestyle frequency."
          plans={[
            {
              tag: "Essentials",          price: "$29/mo",          description: "Unlimited laundry drops.",          features: [
                "12 washes",            "Same-day service",            "Free pickup"],
            },
            {
              tag: "Style & Play",          price: "$59/mo",          description: "Unlimited gaming + salon discount.",          features: [
                "5 salon hours",            "Weekly gaming",            "Exclusive member events"],
            },
            {
              tag: "All-Access",          price: "$99/mo",          description: "Complete service pass.",          features: [
                "Full laundry coverage",            "Priority salon booking",            "Unlimited gaming access"],
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
