/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import React, { useState } from "react";
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";
import { Gamepad2, Clock, CreditCard, Coffee, Plus, Minus, Check, ShoppingBag, Sparkles, Calendar, CheckCircle2, ShieldCheck } from "lucide-react";

const items = [
  {
    title: "Premium Laundry",
    description: "Eco-friendly, fast, and reliable.",
    imageSrc: "http://img.b2bpic.net/free-photo/shirts-jackets-hangers-closet-capsule-wardrobe_169016-71050.jpg"
  },
  {
    title: "Style Salon",
    description: "Expert cuts and wellness.",
    imageSrc: "http://img.b2bpic.net/free-photo/barber-shop-retro-vintage-style_1150-17931.jpg"
  },
  {
    title: "Gaming Lounge",
    description: "Next-gen consoles and PCs.",
    imageSrc: "http://img.b2bpic.net/free-photo/excited-customers-testing-vr-software_74855-1836.jpg"
  },
  {
    title: "Express Folding",
    description: "Done in under an hour.",
    imageSrc: "http://img.b2bpic.net/free-photo/woman-carrying-weaved-laundry-basket-lifestyle-concept_53876-123647.jpg"
  },
  {
    title: "Beauty Treatments",
    description: "Full spa pampering services.",
    imageSrc: "http://img.b2bpic.net/free-photo/make-up-products_23-2148553409.jpg"
  },
  {
    title: "Esports Arena",
    description: "Compete with the best.",
    imageSrc: "http://img.b2bpic.net/free-photo/two-young-indian-people-having-fun-with-new-technology-vr-headset-virtual-reality-simulator_627829-9531.jpg"
  },
  {
    title: "Hub Lounge",
    description: "Community workspace & cafe.",
    imageSrc: "http://img.b2bpic.net/free-photo/team-multiethnic-call-center-workers-using-ai-chatbot-reply-customer-queries_482257-125156.jpg"
  }
];

type FeatureItem = {
  title: string;
  description: string;
  href?: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesImageBentoProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  items: [FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem, FeatureItem];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const ServicesInline = () => {
  const gridClasses = [
    "md:col-span-2",
    "md:col-span-4",
    "md:col-span-3",
    "md:col-span-3",
    "md:col-span-2",
    "md:col-span-2",
    "md:col-span-2",
  ];

  const staggerDelays = [
    0,
    0.1,
    0,
    0.1,
    0,
    0.1,
    0.2,
  ];

  return (
    <section aria-label="Features image bento section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Core Services"}</p>
          </div>

          <TextAnimation
            text={"Everything Under One Roof"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Explore our curated lifestyle hub designed for maximum convenience and fun."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary" animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="w-content-width mx-auto grid grid-cols-1 md:grid-cols-6 gap-3">
          {items.map((item, index) => {
            const content = (
              <div className="relative h-80 xl:h-100 2xl:h-120 overflow-hidden">
                <ImageOrVideo
                  imageSrc={item.imageSrc}
                  videoSrc={item.videoSrc}
                  className="rounded group-hover:scale-105 transition-transform duration-500"
                />

                <div className="absolute inset-x-5 bottom-5 xl:inset-x-6 xl:bottom-6 2xl:inset-x-7 2xl:bottom-7 flex flex-col text-background">
                  <span className="text-2xl font-semibold leading-snug truncate">{item.title}</span>
                  <span className="text-base leading-snug truncate">{item.description}</span>
                </div>
              </div>
            );

            return (
              <ScrollReveal key={index} variant="fade" delay={staggerDelays[index]} className={cls("col-span-1 group", gridClasses[index])}>
                {item.href ? (
                  <a href={item.href} className="block overflow-hidden rounded">
                    {content}
                  </a>
                ) : (
                  <div className="overflow-hidden rounded">
                    {content}
                  </div>
                )}
              </ScrollReveal>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default function ServicesSection() {
  return (
    <div data-webild-section="services" data-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
