// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
        <SectionErrorBoundary name="services">
              <FeaturesImageBento
          tag="Our Core Services"
          title="Everything Under One Roof"
          description="Explore our curated lifestyle hub designed for maximum convenience and fun."
          items={[
            {
              title: "Premium Laundry",          description: "Eco-friendly, fast, and reliable.",          imageSrc: "http://img.b2bpic.net/free-photo/shirts-jackets-hangers-closet-capsule-wardrobe_169016-71050.jpg"},
            {
              title: "Style Salon",          description: "Expert cuts and wellness.",          imageSrc: "http://img.b2bpic.net/free-photo/barber-shop-retro-vintage-style_1150-17931.jpg"},
            {
              title: "Gaming Lounge",          description: "Next-gen consoles and PCs.",          imageSrc: "http://img.b2bpic.net/free-photo/excited-customers-testing-vr-software_74855-1836.jpg"},
            {
              title: "Express Folding",          description: "Done in under an hour.",          imageSrc: "http://img.b2bpic.net/free-photo/woman-carrying-weaved-laundry-basket-lifestyle-concept_53876-123647.jpg"},
            {
              title: "Beauty Treatments",          description: "Full spa pampering services.",          imageSrc: "http://img.b2bpic.net/free-photo/make-up-products_23-2148553409.jpg"},
            {
              title: "Esports Arena",          description: "Compete with the best.",          imageSrc: "http://img.b2bpic.net/free-photo/two-young-indian-people-having-fun-with-new-technology-vr-headset-virtual-reality-simulator_627829-9531.jpg"},
            {
              title: "Hub Lounge",          description: "Community workspace & cafe.",          imageSrc: "http://img.b2bpic.net/free-photo/team-multiethnic-call-center-workers-using-ai-chatbot-reply-customer-queries_482257-125156.jpg"},
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
