// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamListCards from '@/components/sections/team/TeamListCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
        <SectionErrorBoundary name="team">
              <TeamListCards
          tag="Expert Staff"
          title="Meet Your Local Experts"
          description="Friendly professionals ready to help."
          groups={[
            {
              title: "Laundry & Salon Team",          members: [
                {
                  name: "Sarah J.",              role: "Head Stylist",              detail: "10 years experience.",              imageSrc: "http://img.b2bpic.net/free-photo/confident-young-beautiful-female-barber-uniform-grabbed-hair-isolated-green-wall_141793-105669.jpg"},
                {
                  name: "Mike D.",              role: "Laundry Mgr",              detail: "Operations expert.",              imageSrc: "http://img.b2bpic.net/free-photo/woman-choosing-clothes-from-clothes-rack_1170-816.jpg"},
              ],
            },
            {
              title: "Game Tech Support",          members: [
                {
                  name: "Leo K.",              role: "Lounge Mgr",              detail: "Hardware specialist.",              imageSrc: "http://img.b2bpic.net/free-photo/data-center-software-developer-using-pc-monitor-neural-network-ai-visualization-woman-working_482257-135341.jpg"},
              ],
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
