// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialMarqueeCards from '@/components/sections/testimonial/TestimonialMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialMarqueeCards
          tag="Customer Stories"
          title="Love from Our Neighbors"
          description="Hear what our community says about us."
          testimonials={[
            {
              name: "Sarah Miller",          role: "Designer",          quote: "The laundry is fast and the salon is top-tier!",          imageSrc: "http://img.b2bpic.net/free-photo/blond-businessman-happy-expression_1194-3706.jpg"},
            {
              name: "Tom Baker",          role: "Gamer",          quote: "Best gaming setup in town, bar none.",          imageSrc: "http://img.b2bpic.net/free-photo/beautiful-woman-cafe_273609-12867.jpg"},
            {
              name: "Emily Chen",          role: "Student",          quote: "Love coming here to relax and get stuff done.",          imageSrc: "http://img.b2bpic.net/free-photo/older-woman-drinking-coffee-smiling-house-white-shirt-daytime_176474-4942.jpg"},
            {
              name: "David Wilson",          role: "Artist",          quote: "So convenient having everything in one place.",          imageSrc: "http://img.b2bpic.net/free-photo/emotional-female-portrait-closeup-outdoors_1321-4437.jpg"},
            {
              name: "Jessica R.",          role: "Teacher",          quote: "Staff are friendly and the place is spotless.",          imageSrc: "http://img.b2bpic.net/free-photo/happy-teenage-girl-emotions-concept-emotion-happiness_169016-66569.jpg"},
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
